### ISSUE TITLE
Proof read

### ISSUE THREAD

**Issue by rhattersley** [cf-metadata/cf-conventions#3]
Compare [the original v1.6](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.6/build/cf-conventions.html) with the [AsciiDoc version](http://cf-metadata.github.io/) and raise issues and/or submit PRs as required.

NB. A section should be ticked off once any necessary issues and/or PRs have been created. It does not need to wait for those issues/PRs to be resolved.

- [x] Front matter (including Abstract) - @rhattersley. See #25 and #26.
- [x] Preface - @rhattersley. See #14.
- [x] 1. Introduction - @davidhassell. See #2.
- [x] 2. NetCDF Files and Components - @davidhassell. See #28.
- [x] 3. Description of the Data - @rhattersley. See #7 and #29.
- [x] 4. Coordinate Types - @rhattersley. See #8 and #9.
- [x] 5. Coordinate Systems - @rhattersley. See #15 and #16.
- [x] 6. Labels and Alternative Coordinates - @rhattersley. See #10.
- [x] 7. Data Representative of Cells - @rhattersley. See #17.
- [x] 8. Reduction of Dataset Size - @rhattersley. See #18.
- [x] 9. Discrete Sampling Geometries - @rhattersley
- [x] Appendix A: Attributes - @rhattersley. See #19.
- [x] Appendix B: Standard Name Table Format - @rhattersley. See #20.
- [x] Appendix C: Standard Name Modifiers - @rhattersley. See #11.
- [x] Appendix D: Dimensionless Vertical Coordinates - @rhattersley. See #21.
- [x] Appendix E: Cell Methods - @rhattersley. See #12.
- [x] Appendix F: Grid Mappings - @rhattersley. See #22.
- [x] Appendix G: Revision History - @rhattersley. See #13.
- [x] Appendix H: Annotated Examples of Discrete Geometries - @rhattersley. See #23.
- [x] Bibliography - @rhattersley. See #24.

**Comment by rhattersley** [comment]
@davidhassell - are you still intending to review chapter 2?

**Comment by rhattersley** [comment]
Closing, as all the planned actions have been completed. Other problems can be tracked in their own issues.
